{% set data = load_setup_py_data() %}

package:
  name: rpreactor
  version: {{ data['version'] }}

source:
  path: ..

build:
  # Build from the setup.py instructions (inherit its constraints)
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed -vv .
  noarch: python

requirements:
  # Those are conda packages (not pip); the conda channel is specified at the CLI level and not in this file.
  host:
    - python
    - pip
  run:
    - python
    - pebble=4.5
    - rdkit=2019.03.1.0

test:
  source_files:
    - tests
  requires:
    - pytest
  imports:
    - rpreactor
  commands:
    - python -m rpreactor.cli --help
    - pytest tests -v

about:
  home: https://github.com/brsynth/rpreactor
  summary: {{ data['description'] }}
  license: {{ data.get('license') }}
  license_file: LICENSE

extra:
  recipe-maintainers:
    # GitHub IDs for maintainers of the recipe.
    # Always check with the people listed below if they are OK becoming maintainers of the recipe. (There will be spam!)
    - tduigou
