# Details on parameters...
# JOB_DIR:          str, output directory
# IN_RULES:         str, file containing rules
# RADIUS_TO_KEEP:   str, radius to consider. If several, use spaces as value
#                   separator.
# MAX_CUTOFF:       int, maximal substrate occurence. Substrate appearing more
#                   than MAX_CUTOFF will be removed from the wish list 
# MIN_CUTOFF:       int, minimal substrate occurence.
# FILTER_RULES:     list, path to a file (or "None") to be used for filtering
#                   out specific from the final wish list of rules. If list is
#                   empty no attempt will be made to flter out rules.
JOB_DIR: 'job/201901'
IN_RULES: 'data/mnx_20181203/rule/aroaam_nostereo_final/rules_rall.tsv'
RADIUS_TO_KEEP: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
MAX_CUTOFF: 99999
MIN_CUTOFF: 1
FILTER_RULES: []
